# Data Cleaning and Preprocessing from Scratch

This notebook teaches:

- What is data cleaning
- Why raw data is rarely usable
- Structured vs unstructured data
- Real-world examples of messy data
- Missing values
- Duplicate rows
- Wrong spellings
- Inconsistent formats
- Wrong data types
- Outliers

We will also create a **dummy messy dataset** and clean it step by step with explanation for each line.

## 1. What is Data Cleaning?

**Data cleaning** means finding and fixing problems in data so it becomes usable for analysis, dashboards, reporting, or machine learning.

Raw data from the real world is often messy. It may contain:

- missing values
- duplicate rows
- wrong spellings
- inconsistent formats
- wrong data types
- impossible or extreme values

If we do not clean the data, our analysis can become wrong.

## 2. Why Raw Data is Rarely Usable

Real-world data comes from many sources:

- manual entry by humans
- Excel files
- forms
- mobile apps
- APIs
- databases
- scraped websites

Because of that, data usually contains mistakes.

### Example problems
- A person's age may be written as `"25"`, `"twenty five"`, or `250`
- Gender may appear as `"Male"`, `"male"`, `"M"`, `"m"`
- A date may appear as `2025-01-05`, `05/01/2025`, or `Jan 5 2025`
- Salary may be stored as text like `"50,000"` instead of a number
- The same customer may appear multiple times

So before analysis, we clean the dataset.

## 3. Structured vs Unstructured Data

### Structured Data
Structured data has a clear table-like format.

Examples:
- Excel sheet
- SQL table
- CSV file
- sales records
- student marks table

Example:

| name | age | city |
|---|---:|---|
| Ram | 23 | Kathmandu |
| Sita | 21 | Pokhara |

### Unstructured Data
Unstructured data does not come in a neat table.

Examples:
- emails
- PDFs
- customer reviews
- audio
- video
- images
- social media posts

Example:
> "The delivery was late and the product box was damaged."

That sentence has useful information, but it is not in rows and columns.

### Semi-structured Data
This is in between.

Examples:
- JSON
- XML
- log files

These have some structure, but not as clean as a normal table.

## 4. Why We Need Data Cleaning

We clean data because:

1. wrong data gives wrong insights  
2. machine learning models need proper input  
3. dashboards and reports break with dirty data  
4. duplicate records can overcount things  
5. bad text formats reduce accuracy  
6. missing values can create bias or errors  

### Real-world examples
- In banking, wrong customer age can affect loan decisions
- In hospitals, missing patient records can affect treatment
- In e-commerce, duplicate orders can inflate revenue
- In stock analysis, wrong price type can distort indicators
- In education, wrong marks can lead to wrong student ranking

## 5. Create a Dummy Messy Dataset

We will build one small messy dataset that contains many common problems:

- missing values
- duplicate rows
- wrong spellings
- inconsistent text formatting
- wrong data types
- outliers

This is the best way to learn because you can see the problem clearly.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# We create a Python dictionary.
# Each key becomes a column name in the DataFrame.
# Each value is a list of entries for that column.

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Ram", "Shyam", None, "Bikash", "sita", "Anu "],
    "Age": [25, "22", None, 130, 25, "twenty", 19, 21, "22 ", -5],
    "Gender": ["Male", "female", "M", "F", "Male", "male ", None, "Female", "FEMALE", "f"],
    "City": ["Kathmandu", "Pokhara", "ktm", "Lalitpur", "Kathmandu", "Pokhara ", "Biratnagar", None, "pokhara", " lalitpur"],
    "Join_Date": ["2024-01-15", "15/02/2024", None, "March 5 2024", "2024-01-15", "2024/06/01", "2024-13-01", "2024-07-10", "15/02/2024", "2024-08-20"],
    "Salary": [50000, "60,000", None, 9999999, 50000, "45000", 30000, "not available", 60000, 52000]
}

# Convert the dictionary into a pandas DataFrame.
df = pd.DataFrame(data)

# Show the DataFrame.
df

     Name     Age  Gender        City     Join_Date         Salary
0     Ram      25    Male   Kathmandu    2024-01-15          50000
1    Sita      22  female     Pokhara    15/02/2024         60,000
2    Hari    None       M         ktm          None           None
3    Gita     130       F    Lalitpur  March 5 2024        9999999
4     Ram      25    Male   Kathmandu    2024-01-15          50000
5   Shyam  twenty   male     Pokhara     2024/06/01          45000
6    None      19    None  Biratnagar    2024-13-01          30000
7  Bikash      21  Female        None    2024-07-10  not available
8    sita     22   FEMALE     pokhara    15/02/2024          60000
9    Anu       -5       f    lalitpur    2024-08-20          52000

## 6. First Look at the Data

Before cleaning, always inspect the dataset first.

In [3]:
# head() shows the first 5 rows by default.
# It helps us quickly inspect what the data looks like.
df.head()

   Name   Age  Gender       City     Join_Date   Salary
0   Ram    25    Male  Kathmandu    2024-01-15    50000
1  Sita    22  female    Pokhara    15/02/2024   60,000
2  Hari  None       M        ktm          None     None
3  Gita   130       F   Lalitpur  March 5 2024  9999999
4   Ram    25    Male  Kathmandu    2024-01-15    50000

In [16]:
df.columns

Index(['Name', 'Age', 'Gender', 'City', 'Join_Date', 'Salary'], dtype='object')

In [17]:
df["Gender"].unique()

array(['Male', 'female', 'M', 'F', 'male ', None, 'Female', 'FEMALE', 'f'],
      dtype=object)

In [4]:
# shape tells us the number of rows and columns.
# Output format is: (rows, columns)
df.shape

(10, 6)

In [5]:
# info() gives a summary of the dataset.
# It shows:
# - column names
# - number of non-null values
# - detected data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       9 non-null      object
 1   Age        9 non-null      object
 2   Gender     9 non-null      object
 3   City       9 non-null      object
 4   Join_Date  9 non-null      object
 5   Salary     9 non-null      object
dtypes: object(6)
memory usage: 612.0+ bytes

From `info()` we can already notice problems:

- many columns are stored as `object`
- some values are missing
- age and salary are not clean numeric columns
- join date is not a proper datetime column yet

## 7. Missing Values

Missing values mean some information is not present.

Examples:
- age not entered
- city unknown
- join date not recorded
- salary unavailable

Let's detect them.

In [6]:
# isnull() returns True where the value is missing.
df.isnull()

    Name    Age  Gender   City  Join_Date  Salary
0  False  False   False  False      False   False
1  False  False   False  False      False   False
2  False   True   False  False       True    True
3  False  False   False  False      False   False
4  False  False   False  False      False   False
5  False  False   False  False      False   False
6   True  False    True  False      False   False
7  False  False   False   True      False   False
8  False  False   False  False      False   False
9  False  False   False  False      False   False

In [7]:
# isnull().sum() counts missing values in each column.
df.isnull().sum()

Name         1
Age          1
Gender       1
City         1
Join_Date    1
Salary       1
dtype: int64

In [8]:
# We can also calculate missing percentage for each column.
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage

Name         10.0
Age          10.0
Gender       10.0
City         10.0
Join_Date    10.0
Salary       10.0
dtype: float64

## 8. Duplicate Rows

Duplicate rows mean the same record appears more than once.

This can happen because:
- the same form was submitted twice
- the same row was copied multiple times
- data was merged badly

In [9]:
# duplicated() returns True for rows that are duplicates.
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [10]:
# Count how many duplicate rows exist.
df.duplicated().sum()

np.int64(1)

## 9. Wrong Spellings and Inconsistent Formats

Real-world text is often inconsistent.

Examples:
- `Pokhara`, `pokhara`, `Pokhara `
- `Male`, `male`, `M`, `f`
- `Anu ` has extra space
- `ktm` is an abbreviation of Kathmandu

Let's inspect unique values.

In [11]:
# unique() shows distinct values in a column.
df["Gender"].unique()

array(['Male', 'female', 'M', 'F', 'male ', None, 'Female', 'FEMALE', 'f'],
      dtype=object)

In [12]:
df["City"].unique()

array(['Kathmandu', 'Pokhara', 'ktm', 'Lalitpur', 'Pokhara ',
       'Biratnagar', None, 'pokhara', ' lalitpur'], dtype=object)

## 10. Wrong Data Types

A data type tells Python what kind of value a column contains.

Examples:
- integer
- float
- string
- datetime

In our dataset:
- `Age` should be numeric
- `Salary` should be numeric
- `Join_Date` should be datetime

But right now they are messy.

In [13]:
# Check the current data types of all columns.
df.dtypes

Name         object
Age          object
Gender       object
City         object
Join_Date    object
Salary       object
dtype: object

## 11. Outliers

Outliers are values that are extremely different from the rest.

Examples in our data:
- Age = 130
- Age = -5
- Salary = 9999999

Some outliers are real.
Some are data entry errors.
We must inspect them carefully.

In [14]:
# describe(include='all') gives a broad summary.
# For numeric columns, it shows count, mean, min, max, etc.
# For object columns, it shows count, unique values, top value, and frequency.
df.describe(include="all")

       Name  Age Gender       City   Join_Date  Salary
count     9    9      9          9           9       9
unique    8    8      8          8           7       8
top     Ram   25   Male  Kathmandu  2024-01-15   50000
freq      2    2      2          2           2       2

# 12. Cleaning Step by Step

Now we will clean the dataset properly.

We will:
1. copy the original data
2. clean text formatting
3. remove duplicates
4. fix gender values
5. standardize city names
6. fix age
7. fix salary
8. fix join date
9. handle missing values
10. inspect final cleaned dataset

In [ ]:
# Make a copy so the original raw data stays unchanged.
clean_df = df.copy()

# Show the copied version.
clean_df

## 12.1 Clean Column Names

Good column names are easier to work with.
We usually:
- convert to lowercase
- replace spaces with underscores

In [ ]:
# str.lower() converts column names to lowercase.
# str.strip() removes extra spaces from the start and end.
# str.replace(" ", "_") replaces spaces with underscores.
clean_df.columns = clean_df.columns.str.lower().str.strip().str.replace(" ", "_")

clean_df.columns

## 12.2 Clean Basic Text Formatting

We clean text columns by:
- removing extra spaces
- converting to consistent case

In [ ]:
# We select text columns manually.
text_columns = ["name", "gender", "city", "join_date"]

# Loop through each text column.
for col in text_columns:
    # astype("string") converts values to pandas string type.
    # str.strip() removes leading and trailing spaces.
    clean_df[col] = clean_df[col].astype("string").str.strip()

clean_df

## 12.3 Remove Duplicate Rows

We saw one duplicate row earlier.
Now we remove it.

In [ ]:
# drop_duplicates() removes exact duplicate rows.
clean_df = clean_df.drop_duplicates()

# Reset index to make row numbering clean again.
clean_df = clean_df.reset_index(drop=True)

clean_df

## 12.4 Standardize Gender Values

Current gender values are inconsistent:
- Male
- female
- M
- F
- male
- f

We map them into standard values: `Male` and `Female`.

In [ ]:
# First convert everything to lowercase for easier matching.
clean_df["gender"] = clean_df["gender"].str.lower()

# replace() changes old values into new values.
clean_df["gender"] = clean_df["gender"].replace({
    "m": "male",
    "male": "male",
    "f": "female",
    "female": "female"
})

# Convert into title case so output looks clean.
clean_df["gender"] = clean_df["gender"].str.title()

clean_df["gender"]

## 12.5 Standardize City Names

Cities are also inconsistent:
- Kathmandu
- ktm
- Pokhara
- pokhara
- Pokhara
- lalitpur with extra space

We standardize them.

In [ ]:
# Convert all city names to lowercase first.
clean_df["city"] = clean_df["city"].str.lower()

# Replace abbreviations and inconsistent entries with standard names.
clean_df["city"] = clean_df["city"].replace({
    "ktm": "kathmandu"
})

# Use title() to make city names look proper.
clean_df["city"] = clean_df["city"].str.title()

clean_df["city"]

## 12.6 Fix Age Column

Problems in age:
- numbers stored as strings
- `twenty` is text, not numeric
- missing value
- impossible values like `130` and `-5`

We first convert age to numeric.

In [ ]:
# to_numeric() tries to convert values into numbers.
# errors='coerce' means invalid values become NaN.
clean_df["age"] = pd.to_numeric(clean_df["age"], errors="coerce")

clean_df["age"]

In [ ]:
# Let's inspect age statistics after conversion.
clean_df["age"].describe()

In [ ]:
# Mark impossible ages as missing.
# Here we assume valid human age is between 0 and 100.
clean_df.loc[(clean_df["age"] < 0) | (clean_df["age"] > 100), "age"] = np.nan

clean_df["age"]

Now we fill missing age values.

A common method is the **median** because it is less affected by outliers than the mean.

In [ ]:
# median() calculates the middle value.
age_median = clean_df["age"].median()

# fillna() replaces missing values with the median.
clean_df["age"] = clean_df["age"].fillna(age_median)

clean_df["age"]

## 12.7 Fix Salary Column

Problems in salary:
- `60,000` has a comma
- `not available` is text
- one missing value
- one extreme outlier: `9999999`

Let's clean it.

In [ ]:
# Convert salary to string first so we can safely use string operations.
clean_df["salary"] = clean_df["salary"].astype("string")

# Remove commas from salary text.
clean_df["salary"] = clean_df["salary"].str.replace(",", "", regex=False)

# Convert cleaned salary text into numeric.
# Invalid values become NaN.
clean_df["salary"] = pd.to_numeric(clean_df["salary"], errors="coerce")

clean_df["salary"]

In [ ]:
# Inspect salary statistics.
clean_df["salary"].describe()

The salary `9999999` is too large compared to the rest.
This is likely an outlier or data entry error.

For this teaching example, we will mark salary above 200000 as missing.

In [ ]:
# Replace unrealistic salary values with NaN.
clean_df.loc[clean_df["salary"] > 200000, "salary"] = np.nan

clean_df["salary"]

In [ ]:
# Fill missing salary with the median salary.
salary_median = clean_df["salary"].median()
clean_df["salary"] = clean_df["salary"].fillna(salary_median)

clean_df["salary"]

## 12.8 Fix Join Date

Our join date column contains many formats:
- `2024-01-15`
- `15/02/2024`
- `March 5 2024`
- `2024/06/01`
- invalid date like `2024-13-01`

We convert it into proper datetime.

In [ ]:
# to_datetime() converts date text into real datetime values.
# errors='coerce' changes invalid dates into NaT (missing datetime).
clean_df["join_date"] = pd.to_datetime(clean_df["join_date"], errors="coerce")

clean_df["join_date"]

Now we fill missing join dates.

For this demo, we use forward fill, which means:
- take the previous valid date and use it for the missing row

This is not always the correct method in real work, but it is useful for learning.

In [ ]:
# ffill() means forward fill.
clean_df["join_date"] = clean_df["join_date"].ffill()

clean_df["join_date"]

## 12.9 Fill Missing Gender, City, and Name

For text/categorical columns, a common option is the **mode**.
Mode means the most frequent value.

In [ ]:
# Fill missing gender with the mode.
gender_mode = clean_df["gender"].mode()[0]
clean_df["gender"] = clean_df["gender"].fillna(gender_mode)

# Fill missing city with the mode.
city_mode = clean_df["city"].mode()[0]
clean_df["city"] = clean_df["city"].fillna(city_mode)

# Fill missing name with a placeholder.
clean_df["name"] = clean_df["name"].fillna("Unknown")

clean_df

## 13. Final Cleaned Dataset
Let's inspect the cleaned data now.

In [ ]:
clean_df

In [ ]:
clean_df.info()

In [ ]:
clean_df.isnull().sum()

## 14. Compare Raw vs Cleaned Data
This helps students understand the effect of cleaning.

In [ ]:
print("Raw Data:")
display(df)

print("\nCleaned Data:")
display(clean_df)