Student Performance Dataset

In [470]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/student_performance_updated_1000.csv')
df

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,Kenneth Murray,Male,85.0,20.0,NaN,1.0,High,72.0,0.8,80.0,True
996,4497.0,Amy Stout,Female,91.0,NaN,86.0,0.0,High,90.0,3.9,80.0,True
997,1886.0,NaN,Male,85.0,8.0,82.0,2.0,Low,68.0,0.4,54.0,False
998,7636.0,Joseph Sherman,Male,88.0,17.0,60.0,2.0,High,85.0,0.9,53.0,True
999,8021.0,Maria Walls,Female,88.0,10.0,90.0,1.0,Medium,NaN,2.4,94.0,True

1) First Looking at the Data

In [471]:
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [472]:
df.columns

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='object')

In [473]:
df["Gender"].unique()

array(['Male', 'Female', nan], dtype=object)

In [474]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB

2) Checking the Missing Values

In [475]:
df.isnull() ## Return the True where values is Missing

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,True,False,False,False,False,True,False,False,False,False,False,False
996,False,False,False,False,True,False,False,False,False,False,False,False
997,False,True,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,True,False,False,False

In [476]:
df.isnull().sum() ## counts Missing Values in each Column

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study Hours                  24
Attendance (%)               41
Online Classes Taken         25
dtype: int64

In [477]:
### Calculating the Missing Percentage for each Columns::
missing_percentage = (df.isnull().mean()) * 100
print(missing_percentage)

StudentID                    4.0
Name                         3.4
Gender                       4.8
AttendanceRate               4.0
StudyHoursPerWeek            5.0
PreviousGrade                3.3
ExtracurricularActivities    4.3
ParentalSupport              2.2
FinalGrade                   4.0
Study Hours                  2.4
Attendance (%)               4.1
Online Classes Taken         2.5
dtype: float64

Droping Rows with Missing Values

In [478]:
# Step 1 - drop only where Name is missing (identity, can't impute)
df = df.dropna(subset=['Name'])
print("after dropna Name:", df.shape)   # 966

after dropna Name: (966, 12)

3) Fill Missing Values::

In [488]:
## It fill with Median of the Final Grade
df['FinalGrade'] = df['FinalGrade'].fillna(df['FinalGrade'].median())
## Numeric to fill with mean
df['StudyHoursPerWeek'] = df['StudyHoursPerWeek'].fillna(df['StudyHoursPerWeek'].mean())
## For the Categorical Data Filling with (most Frequent Repeated Values:: Mode)
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
### Filling the Parental support with the Mode Value
df['ParentalSupport'] = df['ParentalSupport'].fillna(df['ParentalSupport'].mode()[0])
## Fill all numeric columns at once
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())
## Checking Missing values is there or not
df.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Online Classes Taken         0
dtype: int64

4) Checking Data types and Changing it's

In [480]:
print(df.dtypes) ## it show the Column data type
print(df.info())## it show the data type with the non null count together

StudentID                    float64
Name                          object
Gender                        object
AttendanceRate               float64
StudyHoursPerWeek            float64
PreviousGrade                float64
ExtracurricularActivities    float64
ParentalSupport               object
FinalGrade                   float64
Study Hours                  float64
Attendance (%)               float64
Online Classes Taken          object
dtype: object
<class 'pandas.core.frame.DataFrame'>
Index: 966 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  966 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     966 non-null    object
 3   AttendanceRate             966 non-null    float64
 4   StudyHoursPerWeek          966 non-null    float64
 5   PreviousGrade              966 non-null    float64
 6   ExtracurricularActivities  966 non-null    float64
 7   ParentalSupport            966 non-null    object
 8   FinalGrade                 966 non-null    float64
 9   Study Hours                966 non-null    float64
 10  Attendance (%)             966 non-null    float64
 11  Online Classes Taken       942 non-null    object
dtypes: float64(8), object(4)
memory usage: 98.1+ KB
None

In [489]:
### Converting colunms different data type
### Converting the float student Id data type to the int
df['StudentID'] = df['StudentID'].astype(int)
## converting Online Classes taken object to Boolean
df['Online Classes Taken'] = df['Online Classes Taken'].astype(bool)
#### Converting the Object of the Gender to Category::
df['Gender'] = df['Gender'].astype('category')
### converting the extracurricular activities to int
df['ExtracurricularActivities'] = df['ExtracurricularActivities'].astype(int)
### Converting Parental Support to category::
df['ParentalSupport'] = df['ParentalSupport'].astype('category')
#### Converting the String number to actual number of the final grade
df['FinalGrade'] = pd.to_numeric(df['FinalGrade'], errors='coerce')
### errors = corerce turns invalid Values into Nan instead of crashing
df

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Online Classes Taken
0,1,John,Male,85.000000,15.000000,78.000000,1,High,80.0,False
1,2,Sarah,Female,90.000000,20.000000,85.000000,2,Medium,87.0,True
2,3,Alex,Male,78.000000,10.000000,65.000000,0,Low,68.0,False
3,4,Michael,Male,92.000000,25.000000,90.000000,3,High,92.0,False
4,5,Emma,Female,85.462284,18.000000,82.000000,2,Medium,85.0,True
...,...,...,...,...,...,...,...,...,...,...
994,2787,Shannon Porter,Male,78.000000,20.000000,60.000000,0,High,62.0,False
995,5422,Kenneth Murray,Male,85.000000,20.000000,77.602784,1,High,72.0,True
996,4497,Amy Stout,Female,91.000000,17.647443,86.000000,0,High,90.0,True
998,7636,Joseph Sherman,Male,88.000000,17.000000,60.000000,2,High,85.0,True
999,8021,Maria Walls,Female,88.000000,10.000000,90.000000,1,Medium,80.0,True

4) Finding Duplicates and removing duplicates

In [482]:
### Couting Duplicate rows ::
print(df.duplicated().sum())
### View the Duplicated Rows:: with keep method 'last' and 'fast'
print(df[df.duplicated(keep = 'last')])
## Check Duplicates in one column::
print(df['StudentID'].duplicated().sum())

0
Empty DataFrame
Columns: [StudentID, Name, Gender, AttendanceRate, StudyHoursPerWeek, PreviousGrade, ExtracurricularActivities, ParentalSupport, FinalGrade, Study Hours, Attendance (%), Online Classes Taken]
Index: []
80

In [483]:
### Removing the Duplicated Items::
df = df.drop_duplicates() ## it drop all exact duplicate rows
df

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1,John,Male,85.000000,15.000000,78.000000,1,High,80.0,4.8,59.0,False
1,2,Sarah,Female,90.000000,20.000000,85.000000,2,Medium,87.0,2.2,70.0,True
2,3,Alex,Male,78.000000,10.000000,65.000000,0,Low,68.0,4.6,92.0,False
3,4,Michael,Male,92.000000,25.000000,90.000000,3,High,92.0,2.9,96.0,False
4,5,Emma,Female,85.462284,18.000000,82.000000,2,Medium,85.0,4.1,97.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
994,2787,Shannon Porter,Male,78.000000,20.000000,60.000000,0,High,62.0,1.6,70.0,False
995,5422,Kenneth Murray,Male,85.000000,20.000000,77.602784,1,High,72.0,0.8,80.0,True
996,4497,Amy Stout,Female,91.000000,17.647443,86.000000,0,High,90.0,3.9,80.0,True
998,7636,Joseph Sherman,Male,88.000000,17.000000,60.000000,2,High,85.0,0.9,53.0,True
999,8021,Maria Walls,Female,88.000000,10.000000,90.000000,1,Medium,80.0,2.4,94.0,True

In [484]:
df.describe()## it show the statical Description

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade,Study Hours,Attendance (%)
count,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000
mean,5422.248447,85.462284,17.647443,77.602784,1.500000,80.038302,2.400742,77.207343
std,2607.651501,7.192446,6.112229,9.846997,1.028858,9.310843,1.601557,19.085577
min,1.000000,70.000000,8.000000,60.000000,0.000000,62.000000,-5.000000,50.000000
25%,3248.000000,82.000000,12.000000,70.000000,1.000000,72.000000,1.200000,64.000000
50%,5422.000000,85.462284,17.647443,78.000000,1.000000,80.000000,2.400742,77.000000
75%,7675.000000,91.000000,22.000000,86.000000,2.000000,88.000000,3.700000,89.000000
max,9998.000000,95.000000,30.000000,90.000000,3.000000,92.000000,5.000000,200.000000

5) Doing Filters Outliers::

In [485]:
## Removing rows where Attendance > 100
df = df[df['Attendance (%)'] <= 100]
## Removing rows where Study Hours is negative
df = df[df['Study Hours'] >= 0]
### Keep grades between 0 and 100
df = df[(df['FinalGrade'] >= 0) & (df['FinalGrade'] <= 100)]

In [486]:
df = df.drop(columns=['Study Hours', 'Attendance (%)'])
df = df.copy()

6) final Check

In [487]:
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.dtypes)
print(df.info())
df.shape

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Online Classes Taken         0
dtype: int64
0
StudentID                       int64
Name                           object
Gender                       category
AttendanceRate                float64
StudyHoursPerWeek             float64
PreviousGrade                 float64
ExtracurricularActivities       int64
ParentalSupport              category
FinalGrade                    float64
Online Classes Taken             bool
dtype: object
<class 'pandas.core.frame.DataFrame'>
Index: 956 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  956 non-null    int64
 1   Name                       956 non-null    object
 2   Gender                     956 non-null    category
 3   AttendanceRate             956 non-null    float64
 4   StudyHoursPerWeek          956 non-null    float64
 5   PreviousGrade              956 non-null    float64
 6   ExtracurricularActivities  956 non-null    int64
 7   ParentalSupport            956 non-null    category
 8   FinalGrade                 956 non-null    float64
 9   Online Classes Taken       956 non-null    bool
dtypes: bool(1), category(2), float64(4), int64(2), object(1)
memory usage: 62.8+ KB
None

(956, 10)